# Sample .travis.yml for R projects

language: r

sudo: required

notifications:
  email:
    on_success: change

after_failure: 'cat /home/travis/build/dwinter/rensembl/rensembl.Rcheck/00install.out'
